### ISSUE TITLE
How can I change the user's organizational unit

### ISSUE THREAD

**Issue by yuriang85** [DirectoryTree/LdapRecord-Discussions#1]
I am trying to change the OU of a user that has been created previously, for this I use the inside () method. I do dump ($ user) and it shows that in: correct, but nothing happens in the active directory, that is, it maintains the same OU.
Can someone please help me with this.

  // Create user within OU "OU_workers"
        $user = (new User)->inside('ou=OU_workers,dc=local,dc=com');
        $user->cn = 'John Doe';
        $user->samaccountname = 'jdoe';
        $user->unicodePwd = 'SecretPassword';
        $user->userPrincipalName = 'jdoe@acme.org';
        $user->save();
        $user->userAccountControl = 512;
        $user->save();

        // move user to "OU_students"
        $user = User::findByOrFail('samaccountname', 'jdoe');
        $ou = OrganizationalUnit::findByOrFail('ou', 'OU_students');
        $user->inside('ou=OU_students,dc=local,dc=com');
        $user->save();

in the active directory the user maintains the same OU. Why?

**Comment by stevebauman** [comment]
Hi @yuriang85!

That's a great question, and I think my docs are misleading / missing on how to do this.

The `inside()` method is only for **creation** of new objects, not for existing ones.

For existing objects, you must use the `move()` method:

```php
$user = User::findByOrFail('samaccountname', 'jdoe');

$ou = OrganizationalUnit::findByOrFail('ou', 'OU_students');

$user->move($ou);
```

Checking my docs on [LdapRecord.com](https://ldaprecord.com), I don't have anything in there for this, so I'm going to work on that today and close this issue out once they have been added.

Though, I think you've pointed out a flaw in this API... Maybe the `inside()` method should perform a move with existing objects. What are your thoughts?

**Comment by yuriang85** [comment]
Thank you very much for your answer.
From my modest point of view I think it would be helpful for the **inside()** method to make the object move. although it is fine this way using the **move()** method, but make reference in the documentation to avoid confusion.
Sorry if my English is not very good, I speak Spanish.
