### ISSUE TITLE
Ldap laravel  & inertia

### ISSUE THREAD

**Issue by ghost** [DirectoryTree/LdapRecord-Discussions#16]
Hello its possble use ldap record with laravel  & inertiajs?

**Comment by stevebauman** [comment]
Hi @kronhoz93, yes it is 👍 

There's a tutorial on the website to get up and running with Jetstream (which uses Laravel and InteriaJS):

https://ldaprecord.com/docs/laravel/v1/auth/quickstart/

Hope this helps!
