### ISSUE TITLE
Compatible with Lumen 6.3.2?

### ISSUE THREAD

**Issue by gdog2u** [DirectoryTree/LdapRecord-Discussions#3]
I don't see it anywhere in the docs, but is LdapRecord-Laravel compatible with Lumen? As Lumen doesn't have `php artisan vendor:ppublish` I am unsure of how to complete some steps of the install process.

**Comment by stevebauman** [comment]
Hi @gdog2u,

It currently is not compatible with Lumen — but I will work on this compatibility today and see if I can get it shipped 👍

**Comment by stevebauman** [comment]
Hi @gdog2u, I've created a new repository: [LdapRecord-Lumen](https://github.com/DirectoryTree/LdapRecord-Lumen).

Compatibility has been added -- but I'm still writing some tests up. Should have it done today or tomorrow and then its first release will be created 👍 

Then, all you will have to do is require it via composer:

```bash
composer require directorytree/ldaprecord-lumen
```

Register the providers in your `bootstrap/app.php` file:

```php
$app->register(\LdapRecord\Lumen\LdapServiceProvider::class);
$app->register(\LdapRecord\Lumen\LdapAuthServiceProvider::class);
```

Then publish the config file via the command:

```bash
php artisan make:ldap-config
```

And a config file will be generated in the path `config/ldap.php`.

Once published, the file will be loaded automatically via the `LdapServiceProvider`.

Will be creating docs on ldaprecord.com -- stay tuned!

**Comment by gdog2u** [comment]
@stevebauman Thank you very much for the quick response, and the even quicker work! I look forward to using this.

**Comment by stevebauman** [comment]
Hi @gdog2u, no problem at all, happy to help! :smile:

First release is out 🎉 

https://ldaprecord.com/docs/laravel/lumen

You're all set to get started working with Lumen.

However, keep in mind that the authentication driver is not supported, since Lumen does not support the `session` driver out of the box, and there is no way to attach API tokens to LDAP users.
