### ISSUE TITLE
How to append my own role by default?

### ISSUE THREAD

**Issue by diasasx** [DirectoryTree/LdapRecord-Discussions#5]
Hi, is there a way to add default roles, if newly imported users doesnt have them?

In my user controller i have
public function roles()
    {
        return $this->belongsToMany('App\Role')->withTimestamps();
    }

i need to assign by default a role for example with id 8

**Comment by stevebauman** [comment]
Hi @diasasx,

Yes absolutely. Here's you you would do it.

Create a listener for the LdapRecord `Imported` event. Inside this listener, we will synchronize the users Laravel role.

Run the below command to create the listener:

```bash
php artisan make:listener SynchronizeRole --event="\LdapRecord\Laravel\Events\Imported"
```

Then, inside the listener, you have access to the `Imported` event.

This event contains your database `model`, and the LDAP `user`.

You can then check if the users LDAP model contains a particular LDAP group, and synchronize their Laravel role.

Here's an example:

```php
namespace App\Listeners;

use App\Role;
use LdapRecord\Laravel\Events\Imported;

class SynchronizeRole
{
    /**
     * Handle the event.
     *
     * @param  Imported  $event
     * @return void
     */
    public function handle(Imported $event)
    {
        if ($event->ldap->groups()->contains('Group Name')) {
            $role = Role::findOrFail(8);

            $event->model->roles()->sync($role);
        }
    }
}
```

Does this help at all? Please let me know if you need any further code examples or assistance. Thanks!

**Comment by diasasx** [comment]
You are a great help for me, thx a lot!!

  
>Среда, 15 июля 2020, 16:49 +03:00 от Steve Bauman <notifications@github.com>:
> 
> 
>Hi  @diasasx ,
>Yes absolutely. Here's you you would do it.
>Create a listener for the LdapRecord Imported event. Inside this listener, we will synchronize the users Laravel role.
>Run the below command to create the listener:
>php artisan make:listener SynchronizeRole --event="\LdapRecord\Laravel\Events\Imported"
>Then, inside the listener, you have access to the Imported event.
>This event contains your database model, and the LDAP user.
>You can then check if the users LDAP model contains a particular LDAP group, and synchronize their Laravel role.
>Here's an example:
>namespace App\Listeners;
>
>use App\Role;
>use LdapRecord\Laravel\Events\Imported;
>
>class SynchronizeRole
>{
>    /**
>     * Handle the event.
>     *
>     * @param  Imported  $event
>     * @return void
>     */
>    public function handle(Imported $event)
>    {
>        if ($event->ldap->groups()->contains('Group Name')) {
>            $role = Role::findOrFail(8);
>
>            $event->model->roles()->sync($role);
>        }
>    }
>}
>Does this help at all? Please let me know if you need any further code examples or assistance. Thanks!
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
С Уважением
Гончаров Эдуард
+7-961-859-46-93

**Comment by stevebauman** [comment]
Happy to help @diasasx! 😄 

Keep in mind -- the LdapRecord `Imported` event will only fire **once** for each LDAP user in your Laravel application that has not existed previously.

If you need to synchronize user roles on every login, please let me know and I can provide you code for that as well. 👍

**Comment by diasasx** [comment]
Ok, thx a lot!

  
>Среда, 15 июля 2020, 21:55 +03:00 от Steve Bauman <notifications@github.com>:
> 
> 
>Happy to help  @diasasx ! 😄
>Keep in mind -- the LdapRecord Imported event will only fire  once for each LDAP user in your Laravel application that has not existed previously.
>If you need to synchronize user roles on every login, please let me know and I can provide you code for that as well. 👍
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
С Уважением
Гончаров Эдуард
+7-961-859-46-93

**Comment by diasasx** [comment]
Hi, can you help me with fileuploads?
 
I have Posts table
Each post must have multiple files
 
   https://prnt.sc/txqjqq  thats what I have now
Now I have single file — code below,
I need to make several file uploads through the same form,
with relations.
 
 
 
 
if ($file = $request->file('fileUpload')) {
    $name = '№' . $request->input('reg') . '_' . date("Y") . '.' . date("m") . '.' . date("d") . '_' . $file->getClientOriginalName();
    if ($file->move('uploads/incoming/', $name)) {
        $post->fileUpload = $name;

    }
}
 
<input
    type="file"
    name="fileUpload"
    id="fileUpload"
    class="form-control"
>
Can you help with that?
  
>Среда, 15 июля 2020, 21:55 +03:00 от Steve Bauman <notifications@github.com>:
> 
> 
>Happy to help  @diasasx ! 😄
>Keep in mind -- the LdapRecord Imported event will only fire  once for each LDAP user in your Laravel application that has not existed previously.
>If you need to synchronize user roles on every login, please let me know and I can provide you code for that as well. 👍
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
С Уважением
Гончаров Эдуард
+7-961-859-46-93

**Comment by stevebauman** [comment]
Hi @diasasx, I can definitely help you out.

I would suggest using a library to help you easily manage this, such as [spatie media library](https://github.com/spatie/laravel-medialibrary). If you want to use your own method, that's okay too.

From the code you've posted, you could use the `$file->storeAs()` method instead, to help you move the file into the proper storage directory. This method returns the full path of the file after it has successfully moved.

You could also use the `$file->hashName()` method to generate a unique name for the file, instead of using the actual file name (I'll get to why this is beneficial below).

Here's an example:

**From**:

```php
if ($file = $request->file('fileUpload')) {
    $name = '№' . $request->input('reg') . '_' . date("Y") . '.' . date("m") . '.' . date("d") . '_' . $file->getClientOriginalName();
    if ($file->move('uploads/incoming/', $name)) {
        $post->fileUpload = $name;
    }
}
```

**To**:

```php
if ($file = $request->file('fileUpload')) {
    $post->fileUpload = $file->storeAs('uploads/incoming', $file->hashName());
}
```

If you need to store the actual name of the file (using `$file->getClientOriginalName()`), I'd suggest having a separate database column (or database table) to store the actual name of the file, instead of storing the file in your web server with the uploaded file name of the client.

If you store uploaded files with the name that the user has given, you could run into issues with max file lengths (if you're using a Windows host), along with other issues, such as possible invalid characters inside the name of the file.

It's best to use a completely unique file name for permanent file storage inside your web server, save the clients uploaded file name inside of your database, and when a user downloads the file, you return it to them with that name from the database.

I hope this makes sense and has helped. As always, please feel free to ask further questions or assistance! 👍

**Comment by diasasx** [comment]
Hi, that helped a lot,
I changed my code like this:
How can I move it  to another table — that way seems to be most correct
 
if($file = $request->file('fileUpload')) {
    $name = '№' . $request->input('reg') . '_' . date("Y") . '.' . date("m") . '.' . date("d") . '_' . $file->getClientOriginalName();

    $filePath = $request->file('fileUpload')->storeAs('uploads', $name, 'public');

    $post->fileUpload = $name;
    $post->file_path = '/storage/' . $filePath;

}
whole create method below
 
public function postAdminCreate(PostRequest $request)
{

    $user = Auth::user();
    if (!$user) {
        return redirect()->back();
    }

    $post = new Post([

        'title' => $request->input('title'),
        'content' => $request->input('content'),
        'reg' => $request->input('reg'),
        'date' => $request->input('date'),
        'dateout' => $request->input('dateout'),
        'datedue' => $request->input('datedue'),
        'out_reg' => $request->input('out_reg'),
        'destination' => $request->input('destination'),
        'filestorage' => $request->input('filestorage'),
        'connection' => $request->input('connection'),
        'user_creator' => $request->input('user_creator'),

    ]);

    if($file = $request->file('fileUpload')) {
        $name = '№' . $request->input('reg') . '_' . date("Y") . '.' . date("m") . '.' . date("d") . '_' . $file->getClientOriginalName();

        $filePath = $request->file('fileUpload')->storeAs('uploads', $name, 'public');

        $post->fileUpload = $name;
        $post->file_path = '/storage/' . $filePath;

    }

    $post->save();
    $post->tags()->attach($request->input('tags') === null ? [] : $request->input('tags'));
    $post->users()->attach($request->input('users') === null ? [] : $request->input('users'));
    $post->statuses()->attach($request->input('statuses') === null ? [] : $request->input('statuses'));
    $post->doctypes()->attach($request->input('doctypes') === null ? [] : $request->input('doctypes'));
    $post->organizations()->attach($request->input('organizations') === null ? [] : $request->input('organizations'));
    $post->priorities()->attach($request->input('priorities') === null ? [] : $request->input('priorities'));
    $post->departments()->attach($request->input('departments') === null ? [] : $request->input('departments'));

    return redirect()
        ->route('admin.index')
        ->with('info', 'Документ успешно добавлен' /*. $request->input('title')*/);
}
 
 
 
  
>Вторник, 11 августа 2020, 16:59 +03:00 от Steve Bauman <notifications@github.com>:
> 
> 
>Hi  @diasasx , I can definitely help you out.
>I would suggest using a library to help you easily manage this, such as  spatie media library . If you want to use your own method, that's okay too.
>From the code you've posted, you could use the $file->storeAs() method instead, to help you move the file into the proper storage directory. This method returns the full path of the file after it has successfully moved.
>You could also use the $file->hashName() method to generate a unique name for the file, instead of using the actual file name (I'll get to why this is beneficial below).
>Here's an example:
>From :
>if ($file = $request->file('fileUpload')) {
>
>    $name = '№' . $request->input('reg') . '_' . date("Y") . '.' . date("m") . '.' . date("d") . '_' . $file->getClientOriginalName();
>
>    if ($file->move('uploads/incoming/', $name)) {
>
>        $post->fileUpload = $name;
>
>    }
>
>}
>To :
>if ($file = $request->file('fileUpload')) {
>
>    $post->fileUpload = $file->storeAs('uploads/incoming', $file->hashName());
>
>}
>If you need to store the actual name of the file (using $file->getClientOriginalName()), I'd suggest having a separate database column (or database table) to store the actual name of the file, instead of storing the file in your web server with the uploaded file name of the client.
>If you store uploaded files with the name that the user has given, you could run into issues with max file lengths (if you're using a Windows host), along with other issues, such as possible invalid characters.
>It's best to use a completely unique file name for permanent file storage, save the clients uploaded file name, and when a user downloads the file, you return it to them with that name.
>I hope this makes sense and has helped. As always, please feel free to ask further questions or assistance! 👍
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
С Уважением
Гончаров Эдуард
+7-961-859-46-93

**Comment by diasasx** [comment]
Found this method — below
 
how to use it in my button?
 
@isset ($post->fileUpload)
    <A text-decoration: underline' HREF='{{ $post->file_path }}' target=_blank>
    <button type='button' class='btn-success btn-lg' style='height:50px;font-size:20px;margin-top:1.5%'>
        Download file
    </button>
    </A>
@endisset
 
 
Downloading Files
The   download   method may be used to generate a response that forces the user's browser to download the file at the given path. The   download   method accepts a file name as the second argument to the method, which will determine the file name that is seen by the user downloading the file. Finally, you may pass an array of HTTP headers as the third argument to the method:
return Storage::download('file.jpg');

return Storage::download('file.jpg', $name, $headers);

**Comment by stevebauman** [comment]
Since the storage path is not accessible on your Laravel application, you actually need a "Download" route which will return the download response from your web server using the storage file path:

`routes/web.php`:

```php
Route::get('/posts/{post}/download', 'PostsController@download')->name('posts.download');
```

Then inside of your `PostsController`:

```php
public function download(Post $post)
{
     return response()->download($post->file_path, $post->fileName, [
        'Content-Type' => Storage::mimeType($post->file_path),
    ]);
}
```

Then in your HTML:

```blade
@isset($post->fileUpload)
    <a href='{{ route('posts.download', $post) }}' target=_blank>
    <button type='button' class='btn-success btn-lg' style='height:50px;font-size:20px;margin-top:1.5%'>
        Download file
    </button>
    </a>
@endisset
```

Give that a shot! 👍

**Comment by diasasx** [comment]
https://prnt.sc/tyu8ps
 Hi, it worked but partialy
The controller seems to unable to find the file
path seems to be correct — maybe it should be full path?
http:// …. ??
 
 
 
 
File not found at path: storage/uploads/№66_2020.08.12_1-10-770x515.jpg
 
Next one works — if it put it explicitly
 
 
  
>Среда, 12 августа 2020, 16:32 +03:00 от Steve Bauman <notifications@github.com>:
> 
> 
>Since the storage path is not accessible on your Laravel application, you actually need a "Download" route which will return the download response from your web server using the storage file path:
>routes/web.php:
>Route::get('/posts/{post}/download', 'PostsController@download')->name('posts.download');
>Then inside of your PostsController:
>public function download(Post $post)
>
>{
>
>     return response()->download($post->file_path, $post->fileName, [
>
>        'Content-Type' => Storage::mimeType($post->file_path),
>
>    ]);
>
>}
>Then in your HTML:
>@isset($post->fileUpload)
>
>    <A text-decoration: underline' HREF='{{ route('posts.download', $post) }}' target=_blank>
>
>    <button type='button' class='btn-success btn-lg' style='height:50px;font-size:20px;margin-top:1.5%'>
>
>        Download file
>
>    </button>
>
>    </A>
>
>@endisset
>Give that a shot! 👍
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
 
 
С Уважением
Гончаров Эдуард
+7-961-859-46-93

**Comment by diasasx** [comment]
Tried like this — wont work too

 
 
  
>Среда, 12 августа 2020, 16:32 +03:00 от Steve Bauman <notifications@github.com>:
> 
> 
>Since the storage path is not accessible on your Laravel application, you actually need a "Download" route which will return the download response from your web server using the storage file path:
>routes/web.php:
>Route::get('/posts/{post}/download', 'PostsController@download')->name('posts.download');
>Then inside of your PostsController:
>public function download(Post $post)
>
>{
>
>     return response()->download($post->file_path, $post->fileName, [
>
>        'Content-Type' => Storage::mimeType($post->file_path),
>
>    ]);
>
>}
>Then in your HTML:
>@isset($post->fileUpload)
>
>    <A text-decoration: underline' HREF='{{ route('posts.download', $post) }}' target=_blank>
>
>    <button type='button' class='btn-success btn-lg' style='height:50px;font-size:20px;margin-top:1.5%'>
>
>        Download file
>
>    </button>
>
>    </A>
>
>@endisset
>Give that a shot! 👍
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
С Уважением
Гончаров Эдуард
+7-961-859-46-93

**Comment by stevebauman** [comment]
Sorry @diasasx, this is likely something you'll have to debug on your own, I don't have access to your repository, which is crucial for me to understand the application logic and flow. If there's anything LDAP related, I can absolutely help you there.

**Comment by diasasx** [comment]
HI, Need your help again, i have the same code 
 
if($file = $request->file('fileUpload')) {
    $name = '№' . $request->input('reg') . '_' . date("Y") . '.' . date("m") . '.' . date("d") . '_' . $file->getClientOriginalName();
    $filePath = $request->file('fileUpload')->storeAs('uploads', $name, 'public');
    $post->fileUpload = $name;
    $post->file_path = '/storage/' . $filePath;
}
 
It Uploads my file into table POSTS,
here s full code
 
public function postAdminCreate(PostRequest $request)
{

    $user = Auth::user();
    if (!$user) {
        return redirect()->back();
    }

    $post = new Post([

        'title' => $request->input('title'),
        'content' => $request->input('content'),
        'reg' => $request->input('reg'),
        'date' => $request->input('date'),
        'dateout' => $request->input('dateout'),
        'datedue' => $request->input('datedue'),
        'out_reg' => $request->input('out_reg'),
        'filestorage' => $request->input('filestorage'),
        'connection' => $request->input('connection'),
        'user_assigned' => $request->input('user_assigned'),

    ]);


    if($file = $request->file('fileUpload')) {
        $name = '№' . $request->input('reg') . '_' . date("Y") . '.' . date("m") . '.' . date("d") . '_' . $file->getClientOriginalName();
        $filePath = $request->file('fileUpload')->storeAs('uploads', $name, 'public');
        $post->fileUpload = $name;
        $post->file_path = '/storage/' . $filePath;
    }

    $user->posts()->save($post);
    $post->tags()->attach($request->input('tags') === null ? [] : $request->input('tags'));
    $post->statuses()->attach($request->input('statuses') === null ? [] : $request->input('statuses'));
    $post->taskstatuses()->attach($request->input('taskstatuses') === null ? [] : $request->input('taskstatuses'));
    $post->doctypes()->attach($request->input('doctypes') === null ? [] : $request->input('doctypes'));
    $post->organizations()->attach($request->input('organizations') === null ? [] : $request->input('organizations'));
    $post->priorities()->attach($request->input('priorities') === null ? [] : $request->input('priorities'));
    $post->departments()->attach($request->input('departments') === null ? [] : $request->input('departments'));
    $post->filestorages()->attach($request->input('filestorages') === null ? [] : $request->input('filestorages'));

    return redirect()
        ->route('admin.indexMy')
        ->with('info', 'Success' /*. $request->input('title')*/);
}  
How can I move that upload into different table, stil using the same form and the same controller,
for example table name will be FILES
 
So my post would have many files.
 
Thx for the last help — i solved it eventially— works great, you helped me.
 
С Уважением
Гончаров Эдуард
+7-961-859-46-93

**Comment by stevebauman** [comment]
Hi @diasasx, I apologize, but this is out of the scope of support I provide. I only provide dedicated support for my repositories, not for Laravel application consulting.

I really appreciate your understanding :heart:

**Comment by diasasx** [comment]
Ok, about ldapRecord — how to import into my users table all the users from AD?
and sync it every day?
 
Now I only get user when he or she logs in
  
>Четверг, 20 августа 2020, 18:36 +03:00 от Steve Bauman <notifications@github.com>:
> 
> 
>Hi  @diasasx , I apologize, but this is out of the scope of support I provide. I only provide dedicated support for my repositories, not for Laravel application consulting.
>I really appreciate your understanding ❤️
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
С Уважением
Гончаров Эдуард
+7-961-859-46-93

**Comment by stevebauman** [comment]
> Ok, about ldapRecord — how to import into my users table all the users from AD?
and sync it every day?

https://ldaprecord.com/docs/laravel/auth/importing/#scheduling-the-command

Inside of your `app/Console/Kernel.php` file, you can schedule the `ldap:import` command for however frequently you need it to run:

```php
protected function schedule(Schedule $schedule)
{
    // Import LDAP users hourly.
    $schedule->command('ldap:import ldap', ['--no-interaction'])->hourly();
}
```

If you're using a Windows host, you must setup a scheduled task to run the `ldap:import` command on a specific interval.

Let me know if you need assistance setting up that scheduled task.

Hope this helps! 👍

**Comment by diasasx** [comment]
ok, thx a lot

  
>Пятница, 21 августа 2020, 16:54 +03:00 от Steve Bauman <notifications@github.com>:
> 
> 
>Ok, about ldapRecord — how to import into my users table all the users from AD?
>and sync it every day?
https://ldaprecord.com/docs/laravel/auth/importing/#scheduling-the-command
Inside of your app/Console/Kernel.php file, you can schedule the ldap:import command for however frequently you need it to run:
protected function schedule(Schedule $schedule)

{

    // Import LDAP users hourly.

    $schedule->command('ldap:import ldap', ['--no-interaction'])->hourly();

}
If you're using a Windows host, you must setup a scheduled task to run the ldap:import command on a specific interval.
Let me know if you need assistance setting up that scheduled task.
Hope this helps! 👍
—
You are receiving this because you were mentioned.
Reply to this email directly,  view it on GitHub , or  unsubscribe .  
 
С Уважением
Гончаров Эдуард
+7-961-859-46-93
