### ISSUE TITLE
Retrieving all groups from AD

### ISSUE THREAD

**Issue by dbiljak** [DirectoryTree/LdapRecord-Discussions#6]
Is there an easier way o retrieve all groups from AD (including OU-s and CN-s).

I know there is a
Adldap::search()->ous()->get() and Adldap::search()->groups()->get()

that above was from adldap2

looking for something easier

**Comment by stevebauman** [comment]
Hi @dbiljak,

Yup absolutely, this is actually shown in the documentation site as well:

https://ldaprecord.com/docs/common-queries/

```php
// Retrieve all OU's:
$ous = \LdapRecord\Models\ActiveDirectory\OrganizationalUnit::paginate();

// Retrieve all groups:
$groups = \LdapRecord\Models\ActiveDirectory\Group:: paginate();
```

> **Note**: I call the `paginate()` method above instead of `get()` to avoid hitting the maximum `1000` return limit.

**Comment by dbiljak** [comment]
Great, thnx for quick reply.

**Comment by stevebauman** [comment]
Happy to help @dbiljak! 😄
