### ISSUE TITLE
Connection without username or password.

### ISSUE THREAD

**Issue by lucasbspimenta** [DirectoryTree/LdapRecord-Discussions#7]
Hello,
We used to connect do OpenLdap without Username and Password.
It's like a readonly use, to check if the user logged exists and get extra infos.
How to make it work on LdapRecord? On Adldap2 works.
Thanks

**Comment by stevebauman** [comment]
Hi @lucasbspimenta,

Simply set the `username` and `password` to `null` and you're all set to anonymously bind to your server 👍 

```php
use LdapRecord\Connection;

$connection = new Connection([
     'hosts'    => ['192.168.1.1'],
     'port'     => 389,
     'username' => null,
     'password' => null,
]);
```
