### ISSUE TITLE
Non-existent class referenced in LdapRecord-Lumen documentation

### ISSUE THREAD

**Issue by cronoxyd** [DirectoryTree/LdapRecord-Discussions#8]
In the Lumen documentation (https://ldaprecord.com/docs/laravel/lumen), in the section _Installation_ the code snippet references the non-existent (legacy?) class Ldap**Record**ServiceProvider, but it should be LdapServiceProvider.

**Comment by stevebauman** [comment]
Great catch @cronoxyd! Thanks for this. Patching now 👍
